config/routes.rb
MattTarbitOrg::Application.routes.draw do

  root          :to => 'blog#index', :as => :index

  match         'about' => 'blog#about', :as => :about
  match         'archive' => 'blog#archive', :as => :archive
  match         'archive/titles' => 'blog#archives_by_title', :as => :titles
  match         'search' => 'blog#search', :as => :search
  match         'tag' => 'tag#index', :as => :tags
  match         'tag/:name' => 'tag#read', :as => :tag, :constraints => { :name => /[^\/]+/ }
  match         'rss' => 'feed#rss', :as => :rss

  match         'admin' => 'admin#index', :as => :admin
  match         'admin/comments' => 'comment#index', :as => :comments
  match         'admin/library' => 'admin#library', :as => :librarian
  match         'book' => 'book#index', :as => :library
  match         'logout' => 'admin#logout', :as => :logout
  match         'new/book' => 'book#new', :as => :new_book
  match         'new/:variant' => 'entry#new', :as => :new_entry

  match         'hobby_games' => 'blog#hobby_games'
  match         'family_games' => 'blog#family_games'
  match         'cv' => 'blog#cv'

  match ':y(/:m(/:d))' => 'blog#date', :as => :date, 
    :constraints  =>  { :y => /(19|20)\d\d/, :m => /[01]?\d/, :d => /[0-3]?\d/ }

  match ':y/:m/:d/:slug' => 'entry#read', :as => :entry_slug,
    :constraints  =>  { :y => /(19|20)\d\d/, :m => /[01]?\d/, :d => /[0-3]?\d/, :slug => /[a-z0-9._-]+/ }

  match ':controller(/:action(/:id(.:format)))'

end

app/views/admin/amazon.html.erb
<h2><%= @title %></h2>

<%= form_tag do %>
    <%= hidden_field_tag(:next, params[:next]) %>

    <fieldset>
        <legend>Search Details</legend>

        <div class="form-row">
            <div class="label"><label for="words">Keywords:</label></div>
            <div class="input">
                <%= text_field_tag(:keywords, params[:keywords], :style=>'width:250px', :size=>75) %>
                &nbsp;<strong>in search index:</strong>&nbsp;
                <%= select_tag(:search_index, options_for_select(Amazon::Product::CORE_SEARCH_INDICES, params[:search_index]))%>
                &nbsp;
                <%= submit_tag 'Submit', {:class=>'button'} %>
            </div>
        </div>

    </fieldset>

<% end %>

<% if @items -%>

    <div class="f-left" style="width:48%">
        <h3>Primary result</h3>

        <% item = @items.delete_at(0) %>

        <fieldset style="padding-top:0;">
            <div class="f-left" style="margin-top:1em; width:120px; text-align:center;">
                <%= item.image ? link_to(image_tag(item.image, :width=>120, :alt=>item.title, :border=>0, :class=>'border'), item.url) : '&nbsp;' %>
            </div>

            <div class="f-left" style="width:170px; margin-left:1em;">
                <p><strong><%= item.title %></strong> <%= item.creator %></p>
                <dl class="list tiny">
                    <dt>ASIN:</dt>
                    <dd><%= item.asin %></dd>
                    <dt>Link:</dt>
                    <dd><%= link_to 'www.amazon.co.uk', item.associate_url %></dd>
                    <dt>Post:</dt>
                    <dd><%= link_to 'Use this product &rarr;', "#{params[:next]}?asin=#{item.asin}" %></dd>
                </dl>
            </div>

            <div class="clear"></div>
        </fieldset>
    </div>

    <div class="f-right" style="width:48%">
        <h3><%= pluralize(@items.length, 'other result') %></h3>

        <% @items.each do |item| -%>

            <div class="section">
                <div class="f-left" style="width:75px; text-align:center;">
                    <p><%= item.image ? link_to(image_tag(item.image, :width=>60, :alt=>item.title, :border=>0, :class=>'border'), item.url) : '&nbsp;' %></p>
                </div>
                <div class="f-left small" style="width:250px; margin-left:1em;">
                    <p><strong style="color:#333;"><%= item.title %></strong> <%= item.creator %></p>
                    <dl class="list tiny">
                        <dt>ASIN:</dt>
                        <dd><%= item.asin %></dd>
                        <dt>Link:</dt>
                        <dd><%= link_to 'www.amazon.co.uk', item.associate_url %></dd>
                        <dt>Post:</dt>
                        <dd><%= link_to 'Use this product &rarr;', "#{params[:next]}?asin=#{item.asin}" %></dd>
                    </dl>
                </div>
                <div class="clear"></div>
            </div>

        <% end -%>
    </div>

<% end -%>

app/views/admin/index.html.erb
<h2>Entry admin</h2>

<p>
    Create a <%= Entry.variants.map {|v| link_to(v, new_entry_url(:variant=>v)) }.to_sentence(:two_words_connector=>' or ', :last_word_connector=>' or ').html_safe %>.
    Sync <%= link_to 'links', :action=>:sync_from_delicious %> or <%= link_to 'statuses', :action=>:sync_from_twitter %>.
</p>

<div class="hr"><hr /></div>

<div class="fl">Filter by <%= Entry.variants.map {|v| link_to(v, :variant=>v) }.to_sentence(:two_words_connector=>' or ', :last_word_connector=>' or ').html_safe %>.</div>
<%= will_paginate @entries %>
<div class="clear"></div>

<table class="data">
    <tr>
        <th class="center">Variant</th>
        <th width="50%">Entry</th>
        <th class="center">Posted</th>
        <th class="center">Pubd</th>
        <th class="center">Cmts</th>
        <th class="center">Tags</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    <% for entry in @entries -%>
        <tr class="<%= cycle('row0','row1') %>">
            <td class="center small"><%= entry.variant %></td>
            <td>
            <%= case entry.variant
                when 'post'     then entry.title
                when 'link'     then link_to entry.title, entry.url
                when 'quote'    then link_to_if entry.url, ("&#8220;%s&#8221;" % truncate(entry.content, :length=>55)).html_safe, entry.url
                when 'status'   then truncate(entry.content, :length=>55)
                else entry.title
            end %>
            </td>
            <td class="center small"><%= entry.created_at.strftime("%d-%m-%y @ %H:%M") %></td>
            <td class="center"><%= entry.published ? '&bull;'.html_safe : '' %></td>
            <td class="center"><%= entry.comments.length > 0 ? entry.comments.length : '' %></td>
            <td class="center"><%= entry.tags.length > 0 ? entry.tags.length : '' %></td>
            <td class="center"><%= link_to 'View',   entry_url(entry) %></td>
            <td class="center"><%= link_to 'Edit',   {:controller=>:entry, :action=>:edit,   :id=>entry } %></td>
            <td class="center"><%= link_to 'Delete', {:controller=>:entry, :action=>:delete, :id=>entry}, :confirm=>'Are you sure?' %></td>
        </tr>
    <% end -%>
</table>

<%= will_paginate @entries %>

app/views/admin/library.html.erb
<h2>Library admin</h2>

<div class="fl">Create a <%= link_to 'book', new_book_url %>.</div>

<%= will_paginate @books %>

<div class="clear"></div>

<table class="data">
    <tr>
        <th style="width:45%;">Title</th>
        <th style="width:30%;">Author</th>
        <th class="center">Added</th>
        <th></th>
        <th></th>
    </tr>
    <% @books.each_with_index do |book,i| %>
        <tr class="row<%= i%2 %>">
            <td><%= link_to truncate(book.title, :length => 50), {:controller=>:book, :action=>:show, :id=>book } %></td>
            <td><%= linkify_authors(book.authors) %></td>
            <td class="ac small"><%= book.created_at.strftime("%d-%m-%y @ %H:%M") %></td>
            <td class="ac"><%= link_to 'Edit',  {:controller=>:book, :action=>:edit, :id=>book } %></td>
            <td class="ac"><%= link_to 'Delete',    {:controller=>:book, :action=>:delete, :id=>book }, :confirm=>'Are you sure?'  %></td>
        </tr>
    <% end %>
</table>

<%= will_paginate @books %>

app/views/admin/login.html.erb
<h2>Login</h2>

<%= form_rows_for :user, :url=>{:action=>:login} do |f| %>

    <fieldset>
        <legend>Login Details</legend>

        <%= f.text_field :username, :style=>'width:98%', :size=>75 %>
        <%= f.password_field :password, :style=>'width:98%', :size=>75 %>

        <div class="form-row">
            <div class="input">
                <span class="tick-item"><%= check_box_tag 'remember_me' %></span>
                <span class="tick-text"><label for="remember_me">Remember me on this computer</label></span>
            </div>
        </div>

        <div class="form-gap"></div>

        <div class="form-row">
            <div class="input"><%= submit_tag 'Submit', {:class=>'button'} %></div>
        </div>

    </fieldset>

<% end %>