config/routes.rb
MattTarbitOrg::Application.routes.draw do

  root          :to => 'blog#index', :as => :index

  match         'about' => 'blog#about', :as => :about
  match         'archive' => 'blog#archive', :as => :archive
  match         'archive/titles' => 'blog#archives_by_title', :as => :titles
  match         'search' => 'blog#search', :as => :search
  match         'tag' => 'tag#index', :as => :tags
  match         'tag/:name' => 'tag#read', :as => :tag, :constraints => { :name => /[^\/]+/ }
  match         'rss' => 'feed#rss', :as => :rss

  match         'admin' => 'admin#index', :as => :admin
  match         'admin/comments' => 'comment#index', :as => :comments
  match         'admin/library' => 'admin#library', :as => :librarian
  match         'book' => 'book#index', :as => :library
  match         'logout' => 'admin#logout', :as => :logout
  match         'new/book' => 'book#new', :as => :new_book
  match         'new/:variant' => 'entry#new', :as => :new_entry

  match         'hobby_games' => 'blog#hobby_games'
  match         'family_games' => 'blog#family_games'
  match         'cv' => 'blog#cv'

  match ':y(/:m(/:d))' => 'blog#date', :as => :date, 
    :constraints  =>  { :y => /(19|20)\d\d/, :m => /[01]?\d/, :d => /[0-3]?\d/ }

  match ':y/:m/:d/:slug' => 'entry#read', :as => :entry_slug,
    :constraints  =>  { :y => /(19|20)\d\d/, :m => /[01]?\d/, :d => /[0-3]?\d/, :slug => /[a-z0-9._-]+/ }

  match ':controller(/:action(/:id(.:format)))'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :entries, :order=>'created_at DESC'
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/tag_controller.rb
class TagController < ApplicationController
  caches_page :index, :read

  def index
    @tags = Tag.find_by_sql "SELECT t.name, COUNT(*) AS count FROM tags t LEFT JOIN entries_tags e ON t.id = e.tag_id GROUP BY t.id ORDER BY count DESC"
    @title = "Tags"
  end

  def read
    @tag = Tag.find_by_name(params[:name])
    if @tag.nil?
      render :template => 'blog/notfound'
    else
      @title = "Tagged as #{@tag.name}"
    end
  end

end

app/views/tag/index.html.erb
<h2><%= @title %></h2>

<ul id="tags">
<% @tags.each do |t| -%>
    <% size = [(9.5 + (t.count.to_f/2)) / 10, 1.5].min %>
    <% weight = (size > 1.0) ? 'normal' : 'normal' %>
    <li style="font-size:<%=size%>em; font-weight:<%= weight %>;"><%= link_to(t.name, tag_url(:name=>t.name), {:title=>"#{t.count} entries"}) %></li>
<% end -%>
</ul>

<div class="clear"></div>

app/views/tag/read.html.erb
<h2>Tagged as <em><%= @tag.name %></em></h2>

<%= render :partial=>'partials/entries', :object=>@tag.entries %>