config/routes.rb
MattTarbitOrg::Application.routes.draw do

  root          :to => 'blog#index', :as => :index

  match         'about' => 'blog#about', :as => :about
  match         'archive' => 'blog#archive', :as => :archive
  match         'archive/titles' => 'blog#archives_by_title', :as => :titles
  match         'search' => 'blog#search', :as => :search
  match         'tag' => 'tag#index', :as => :tags
  match         'tag/:name' => 'tag#read', :as => :tag, :constraints => { :name => /[^\/]+/ }
  match         'rss' => 'feed#rss', :as => :rss

  match         'admin' => 'admin#index', :as => :admin
  match         'admin/comments' => 'comment#index', :as => :comments
  match         'admin/library' => 'admin#library', :as => :librarian
  match         'book' => 'book#index', :as => :library
  match         'logout' => 'admin#logout', :as => :logout
  match         'new/book' => 'book#new', :as => :new_book
  match         'new/:variant' => 'entry#new', :as => :new_entry

  match         'hobby_games' => 'blog#hobby_games'
  match         'family_games' => 'blog#family_games'
  match         'cv' => 'blog#cv'

  match ':y(/:m(/:d))' => 'blog#date', :as => :date, 
    :constraints  =>  { :y => /(19|20)\d\d/, :m => /[01]?\d/, :d => /[0-3]?\d/ }

  match ':y/:m/:d/:slug' => 'entry#read', :as => :entry_slug,
    :constraints  =>  { :y => /(19|20)\d\d/, :m => /[01]?\d/, :d => /[0-3]?\d/, :slug => /[a-z0-9._-]+/ }

  match ':controller(/:action(/:id(.:format)))'

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  caches_page :index, :archive, :archives_by_title, :date, :about

  def index
    @entries = Entry.published.includes(:comments).order('entries.created_at DESC').limit(20)
    @first_date = @entries.first.created_at
    @books = Book.includes(:authors).order('books.created_at DESC').limit(4)
  end

  def archive
    @dates = Entry.published.counts_by_date
  end

  def archives_by_title
    @entries = Entry.published.order('entries.created_at DESC')
  end

  def date
    y,m,d = [params[:y], params[:m], params[:d]].map {|v| v.to_i if v }
    @entries = Entry.published.find_by_date(y,m,d)
    @format1 = m ? d ? "%e %b %Y" : "%b %Y" : "%Y"
    @format2 = m ? d ? "%Y %m %d" : "%Y %m" : "%Y"
    @title = 'All entries from ' + Time.utc(y,m,d).strftime(@format1)
    @prev = @entries.last.find_prev
    @next = @entries.first.find_next
  end

  def search
    if params[:words]
      @words = split_search_terms(params[:words])
      @entries = Entry.published.find_by_words(@words)
      @title = 'Search results for "%s"' % params[:words]
    else
      @title = 'Search'
    end
  end

  def about
    @count = Entry.published.count(:group=>:variant, :order=>'count_all DESC')
    @total = @count.inject(0) { |sum,a| sum + a.last }
    @books = Book.count
    @authors = Author.count
  end

  def cv
    @single_column = true
  end

  def hobby_games
    @wide_layout = true
  end

  def family_games
    @wide_layout = true
  end

private

  def split_search_terms(str)
    # within quoted text replace spaces with a placeholder
    reg = /\"(.*?)\"/
    str = str.gsub(reg) { |s| s.gsub(/\s/,'[SPACE]') }
    # split on spaces
    words = str.split
    # replace placeholders with spaces and remove quotes
    words.map {|w| w.gsub('[SPACE]',' ').gsub(reg,'\1') }
  end

end

app/views/blog/about.html.erb
<h2>About</h2>

<div class="section">
    <h3>This site belongs to Matthew J. Tarbit</h3>
    <p>
        I come from Newcastle-upon-Tyne, in the North of England, and live in Leeds, in the pretend North of England.
        I'm married to the lovely <a href="http://theyorkshirefork.co.uk">Katie Buffalo</a>, she's a 'murican and the best thing since sliced bread, we met on the internet, it's the future.
    </p>
    <p>
        I've recently finished a long stint working for <a href="http://www.sense.co.uk/">Sense Internet</a>, tying ribbons of PHP, MySQL, HTML, CSS, JavaScript, Flash and ActionScript into pretty bows.
        And am now settling in to the distinctly more Python-flavoured environs of <a href="http://www.isotoma.com/">Isotoma</a> in York.
    </p>
    <p>
        If you've looked at the archives at all you may have noticed there's a gap of 2 years unaccounted for. 
        The entries preceding that lull are from a site called pixelised.com that my brother and I used to run.
        Seemed a shame to let them go to waste.
    </p>
    <p>
        If you'd like to get in touch with me, you can send an email to mtarbit, plus an at-sign, then gmail, with a dot-com.
    </p>
</div>

<div class="section">
    <h3>Colophon</h3>
    <p>
        This website plays host to <%= link_to(pluralize(@total,'entry'), archive_url) %> 
        which can be broken down by type as 
        <%= @count.map{ |a| pluralize(a.last,a.first) }.to_sentence(:last_word_connector=>' and ') %>.
        There's also a library of <%= link_to(pluralize(@books,'book'), library_url) %> by <%= link_to(pluralize(@authors,'author'),{:controller=>'author'}) %>.
    </p>
    <p>
        Entries prior to 2003 were written by <%= link_to('Matt', index_url) %> and <a href="http://www.flickr.com/photos/dtarbit/">Dan Tarbit</a>
        with occasional contributions from <a href="http://www.jonnyram.com">Jonathan Lumb</a>. Unfortunately, attribution for some of the older 
        posts and comments has been obscured by the mists of time.
    </p>
    <p>
        The site is built using the
        <a href="http://www.ruby-lang.org/">Ruby</a> on 
        <a href="http://www.rubyonrails.org/">Rails</a> framework backed by a 
        <a href="http://www.mysql.com/">MySQL</a> database.
        Posts are marked up in the <a href="http://daringfireball.net/projects/markdown/">markdown</a> syntax and parsed by the <a href="http://www.deveiate.org/projects/BlueCloth">BlueCloth</a> gem.
        Code is highlighted with <a href="http://pygments.org/">Pygments</a>.
        Some of the data for links and reviews is obtained via web service APIs. 
        The <a href="http://pablotron.org/software/rubilicious/">rubilicious</a> library is used to sync bookmarks from a <a href="http://del.icio.us/">del.icio.us</a> account, 
        the <a href="http://twitter.rubyforge.org/">twitter</a> gem is used to retrieve my statuses from Twitter
        and the <a href="http://httparty.rubyforge.org/">httparty</a> gem is used to search for and retrieve amazon product details for reviews and associate links.
        Emails are sent via <a href="http://www.rubyinside.com/how-to-use-gmails-smtp-server-with-rails-394.html">Gmail's SMTP service</a> with a helping hand from lib/smtp_tls.rb. 
        The site is served by <a href="http://httpd.apache.org/">Apache 2</a> &amp; <a href="http://www.modrails.com/">mod_rails</a> on a 
        <a href="http://www.linode.com">Linode VPS</a>, shared thanks to the kindly benefaction of <a href="http://www.ukben.com/">Ben Walton</a>. 
        Code is written in 
        <a href="http://macromates.com/">Textmate</a>, 
        <a href="http://www.vim.org/">vim</a>
        and version controlled with the help of
        <a href="http://github.com/mtarbit/matt.tarbit.org/tree">github</a>.
        Icons are used here and there from the free <a href="http://www.famfamfam.com/lab/icons/silk/">silk icon set</a> by Mark James.
    </p>
</div>

<% content_for :sidebar do %>
    <h2>Elsewhere</h2>

    <div class="section">
        <p>
            Parts of me are strewn about the ether.
            Particularly in the following locations:
        </p>

        <ul class="sites">
            <li class="site-tw"><a rel="me" href="http://www.twitter.com/mtarbit">Tweets</a> at Twitter</li>
            <li class="site-dl"><a rel="me" href="http://del.icio.us/pxmatt">Links</a> at Delicious</li>
            <li class="site-fb"><a rel="me" href="http://www.facebook.com/profile.php?id=687311229">Friends</a> at Facebook</li>
            <li class="site-li"><a rel="me" href="http://www.linkedin.com/pub/matt-tarbit/5/809/388">Contacts</a> at LinkedIn</li>
            <li class="site-fl"><a rel="me" href="http://www.flickr.com/photos/36071867@N00/">Photos</a> at Flickr</li>
            <li class="site-lt"><a rel="me" href="http://www.librarything.com/catalog/mtarbit">Books</a> at LibraryThing</li>
            <li class="site-xb"><a rel="me" href="http://live.xbox.com/en-US/profile/profile.aspx?pp=0&amp;GamerTag=Matt+and+Katie">Games</a> at Xbox Live</li>
            <li class="site-lf"><a rel="me" href="http://www.last.fm/user/pxm">Music</a> at Last.fm</li>
            <li class="site-gh"><a rel="me" href="http://www.github.com/mtarbit">Code</a> at GitHub</li>
        </ul>
    </div>      
<% end %>

app/views/blog/archive.html.erb
<div>
    <div style="float:left; width:50%;"><h2>Archive</h2></div>
    <div style="float:right; width:50%; text-align:right;">
        <p style="margin-top:0.6em;">
            <%= link_to(titles_url) do %>
                View archives as list &rarr;
            <% end %>
        </p>
    </div>
    <div class="clear"></div>
</div>

<% Time.now().year.downto(2001) do |y| %>

    <div class="clear"></div>
    <div class="cal-y">

        <% if @dates[y].nil? %>

            <h3><%= y %></h3>
            <p>No entries for this year.</p>

        <% else %>

            <h3><%= link_to(y, date_url(:y=>y)) %></h3>

            <% (1..12).each do |m| %>
                <% month = Time.utc(y,m).strftime("%b") %>
                <% space = '&nbsp;'.html_safe %>

                <div class="cal-m <%= m%6 == 1 ? 'first':'' %>">
                    <small><%= link_to_unless(@dates[y][m].nil?, month, date_url(:y=>y,:m=>m)) %></small>
                    <table class="cal <%= @dates[y][m].nil? ? 'empty' : '' %>">
                        <% 6.times do |i| %>
                            <tr>
                                <% 7.times do |j| %>
                                    <%
                                    d = 1 + ((i*7) + j) - Time.utc(y,m).wday
                                    count = @dates[y][m][d] rescue nil
                                    valid = (d > 0 and d <= Date.civil(y,m,-1).day)
                                    css = valid ? count ? 'in':'on':'off'
                                    str = count ? link_to(space, date_url(:y=>y,:m=>m,:d=>d), :title=>pluralize(count,'entry')) : space
                                    %>
                                    <td width="14%" class="<%= css %>"><%= str %></td>
                                <% end %>
                            </tr>
                        <% end %>
                    </table>
                </div>

            <% end %>

        <% end %>

    </div>

<% end %>

app/views/blog/archives_by_title.html.erb
<div>
    <div style="float:left; width:50%;"><h2>Archives by title</h2></div>
    <div style="float:right; width:50%; text-align:right;">
        <p style="margin-top:0.6em;">
            <%= link_to(archive_url) do %>
                View archives as calendar &rarr;
            <% end %>
        </p>
    </div>
    <div class="clear"></div>
</div>

<% if @entries -%>
    <%  min = 0; max = @entries.size - 1  %>
    <% @entries.each_with_index do |entry,i| -%>
        <%
        this_date = entry.created_at.strftime('%b %Y')
        last_date = (i>min) ? (last_entry = @entries[i-1]).created_at.strftime('%b %Y') : ''
        next_date = (i<max) ? (next_entry = @entries[i+1]).created_at.strftime('%b %Y') : ''
        -%>

        <% if this_date != last_date -%>
            <h4><%= link_to this_date, date_url(:y=>entry.created_at.year, :m=>entry.created_at.month) %></h4>
        <% end -%>


        <% if this_date != last_date -%><ul class="spaced" style="font-size:0.9em;"><% end -%>
            <li><%= link_to truncate(entry.page_title, :length=>75), entry_url(entry) %></li>
        <% if this_date != next_date -%></ul><% end -%>

    <% end -%>
<% end -%>

app/views/blog/cv.html.erb
<div id="hcard-Matt-Tarbit" class="vcard">
    <h2><a class="url fn" href="http://matt.tarbit.org">Matthew Tarbit</a></h2>

    <div class="section">
        <h3>Overview</h3>

        <p style="font-size:1.2em; line-height:1.4em; margin-bottom:1.4em;">
            Fast, neat, hard-working developer with almost a decade's experience. Equally at home with both
            client-side and server-side technologies, often providing the glue between the two.
            A jack of all trades, and master of some. Co-workers come to me with problems and leave with
            solutions.
        </p>

        <div class="download-links">
            <div class="download-link"><a class="icon-vcard" href="http://technorati.com/contacts/<%= cv_url %>">Download vCard to your address book</a></div>
            <div class="download-link"><a class="icon-pdf" href="/files/Matthew Tarbit - CV.pdf">Download a copy of this CV as a PDF</a></div>
            <div class="download-link"><a class="icon-doc" href="/files/Matthew Tarbit - CV.doc">Download a copy of this CV for Word</a></div>
        </div>

        <dl class="list">
            <dt>Current Title:</dt>
            <dd>Senior Web Developer <span class="org">Sense Internet</span></dd>

            <dt>Date of Birth:</dt>
            <dd>1st March 1977</dd>

            <dt>Address:</dt>
            <dd>
                <address class="adr">
                    <span class="street-address">20 Ash Grove</span>,
                    <span>Hyde Park</span>,
                    <span class="locality">Leeds</span>,
                    <span class="region">West Yorkshire</span>,
                    <span class="country-name">UK</span>,
                    <span class="postal-code">LS6 1AY</span>
                </address>
            </dd>

            <dt>Phone:</dt>
            <dd>07724 737672</dd>

            <dt>Email:</dt>
            <dd><a class="email" href="mailto:mtarbit@gmail.com">mtarbit@gmail.com</a></dd>

            <dt>Website:</dt>
            <dd><%= link_to('matt.tarbit.org', index_url, :class=>'url') %></a></dd>
        </dl>
    </div>
</div>

<%
=begin
%>
<div class="section">
    <h3>Overview</h3>

    <p>
        With a background in illustration, I originally entered the industry in a design capacity
        over 9 years ago. However, I quickly found myself drawn to the more technical aspects
        of web development and worked towards becoming proficient in the full spectrum of tasks
        available from front-end to back.
    </p>

    <p>
        As a result, I find myself able to work well both alone, on single-handed builds,
        and with larger teams. Often acting as the glue between designers and programmers, and
        equally at home in both worlds.
    </p>

    <p>
        With the growing prominence of JavaScript and AJAX-driven web applications, I am well positioned
        to drive these aspects of development. Recently building an extensive, robust and re-usable
        library of common UI widgets from scratch alongside a compact effects toolkit for animation and
        drag &amp; drop behaviours.
    </p>

</div>
<%
=end
%>

<div class="section">
    <h3>Technical Skills</h3>

    <h4>8+ years experience</h4>
    <ul>
        <li>HTML, XHTML</li>
        <li>CSS</li>
        <li>JavaScript <small>&mdash; DOM scripting, AJAX, experience of Prototype, jQuery and the Google Maps API</small></li>
        <li>ActionScript <small>&mdash; including AS 3.0</small></li>
        <li>PHP <small>&mdash; including experience of MVC and OO development</small></li>
        <li>MySQL</li>
        <li>Adobe Flash</li>
        <li>Adobe Photoshop</li>
        <li>Adobe Illustrator</li>
        <li>LAMP environment <small>&mdash; familiarity with unix-based operating systems and common shell-oriented tasks</small></li>
    </ul>

    <h4>More recent additions (5 years or less)</h4>
    <ul>
        <li>Ruby, Ruby on Rails <small>&mdash; in which my personal website is built</small></li>
        <li>Subversion, Git</li>
        <li>DVD Production <small>&mdash; with Adobe Encore</small></li>
    </ul>

    <p>
        I have a genuine drive to develop my knowledge of programming and web development and keep up with as many technologies as I can, both emerging and established.
        Alongside my extensive experience in a professional or production setting with those above, I have also experimented with, or written small programs in, the following:
    </p>
    <ul>
        <li>Python/Django, C, Objective-C/Cocoa, LISP/Scheme, Perl</li>
    </ul>

</div>

<div class="section pg">
    <h3>Education &amp; Employment History</h3>

    <dl class="list">
        <dt>2000 &ndash; <%=Time.now.year%>:</dt>
        <dd>Senior Web Developer &mdash; <em><a href="http://www.sense.co.uk">Sense Internet</a></em></dd>

        <dt>1996 &ndash; 1999:</dt>
        <dd>BA (Hons) Graphic Arts and Design &mdash; <em>Leeds Metropolitan University</em></dd>

        <dt>1995 &ndash; 1996:</dt>
        <dd>National Diploma, Foundation Art &amp; Design &mdash; <em>Newcastle College</em></dd>
    </dl>
</div>

<div class="section" id="portfolio">
    <h3>Portfolio</h3>

    <div class="sample">
        <div class="screen"><a href="http://jsframework.sense-dev.com:8080"><img src="<%= asset_path 'cv/thumbs/javascript.png' %>" width="153" height="97" border="0" alt="" /></a></div>
        <div class="detail">
            <h4>JavaScript Toolkit</small></h4>
            <ul class="compact">
                <li class="print">http://jsframework.sense-dev.com:8080</li>
                <li><a href="http://jsframework.sense-dev.com:8080">Library of over 20 UI widgets</a> (DatePicker, Overlay, AutoComplete).</li>
                <li>Compact visual effects toolkit (CSS tweening, drag &amp; drop).</li>
                <li>Widgets can be instantiated with pure markup (no JavaScript required).</li>
                <li>Structured in a name-spaced class hierarchy, supporting extensibility.</li>
                <li>Lightweight debug console for development where FireBug isn't available (Ctrl-Shift-L).</li>
                <li>Build tool for smoother deployment.</li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>

    <div class="sample">
        <div class="screen"><a href="http://www.travelodge.co.uk"><img src="<%= asset_path 'cv/thumbs/travelodge.png' %>" width="153" height="97" border="0" alt="" /></a></div>
        <div class="detail">
            <h4>Travelodge</h4>
            <ul class="compact">
                <li class="print">http://www.travelodge.co.uk</li>
                <li><a href="http://www.travelodge.co.uk">Public website</a> of the UK's biggest budget hotel chain.</li>
                <li>Part of two-man team working on markup &amp; CSS for much of the site's history.</li>
                <li>Following a recent redesign, revamped 3rd party markup &amp; CSS resulting in a reduction in CSS filesize of around 60%.</li>
                <li>Lead developer on Google Maps implementation with custom clustering mechanism.</li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>

    <div class="sample">
        <div class="screen"><a href="http://www.rizla.co.uk"><img src="<%= asset_path 'cv/thumbs/rizla.png' %>" width="153" height="97" border="0" alt="" /></a></div>
        <div class="detail">
            <h4>Rizla</h4>
            <ul class="compact">
                <li class="print">http://www.rizla.co.uk</li>
                <li><a href="http://www.rizla.co.uk">Public website</a> of the UK's biggest rolling paper brand.</li>
                <li>Part of two man team working on markup &amp; CSS for much of the site's history.</li>
                <li>Various branded Flash games (breakout, bowling) including the long-term visitor favourite:
                    <a href="http://www.rizla.co.uk/game-time/?game=rizlajongg">Rizlahjong</a>.
                </li>
                <li>Lead developer on customizable, drag &amp; drop, portal-style homepage.</li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>

    <div class="sample pg">
        <div class="screen"><a href="http://www.bafta-online.org"><img src="<%= asset_path 'cv/thumbs/bafta.png' %>" width="153" height="97" border="0" alt="" /></a></div>
        <div class="detail">
            <h4>Bafta <small>(awaiting launch)</small></h4>
            <ul class="compact">
                <li class="print">http://www.bafta-online.org</li>
                <li><a href="http://www.bafta-online.org">Voting application</a> for the British Academy of Film and Television Arts.</li>
                <li>Primary source of vote data for BAFTA awards.</li>
                <li>Web-based application as replacement for existing downloadable flash applications.</li>
                <li>Sole front-end developer on rich AJAX-driven UI with graceful degradation to fully functional non-JavaScript fallback.</li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>

    <div class="sample">
        <div class="screen"><a href="http://www.imperial-trade.com"><img src="<%= asset_path 'cv/thumbs/imperial.png' %>" width="153" height="97" border="0" alt="" /></a></div>
        <div class="detail">
            <h4>Imperial Tobacco</h4>
            <ul class="compact">
                <li class="print">http://www.imperial-trade.com</li>
                <li><a href="http://www.imperial-trade.com">Trade website</a> of the world's 4th largest Tobacco company.</li>
                <li>Single-handed build (HTML, CSS, JS, PHP &amp; MySQL).</li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>

    <div class="sample">
        <div class="screen"><a href="http://www.warburtons-trade.co.uk"><img src="<%= asset_path 'cv/thumbs/warburtons.png' %>" width="153" height="97" border="0" alt="" /></a></div>
        <div class="detail">
            <h4>Warburtons</h4>
            <ul class="compact">
                <li class="print">http://www.warburtons-trade.co.uk</li>
                <li><a href="http://www.warburtons-trade.co.uk">Trade website</a> of &ldquo;Britain's favourite baker&rdquo;.</li>
                <li>Single-handed build (HTML, CSS, JS, PHP &amp; MySQL).</li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>

    <div class="sample">
        <div class="screen"><a href="http://www.xt3.com"><img src="<%= asset_path 'cv/thumbs/xt3.png' %>" width="153" height="97" border="0" alt="" /></a></div>
        <div class="detail">
            <h4>XT3</h4>
            <ul class="compact">
                <li class="print">http://www.xt3.com</li>
                <li><a href="http://www.xt3.com">Social networking site</a> with around 50,000 members. Established in association with <a href="http://www.wyd2008.org">World Youth Day</a> and the Catholic church.</li>
                <li>Lead initial design work (including current logo).</li>
                <li>JavaScript developer on AJAX-driven interactions used throughout the site.</li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>

    <div class="sample">
        <div class="detail">
            <h4>Helly Hansen <small>(2001-2004)</small></h4>
            <ul class="compact">
                <li class="print">http://www.hellyhansen.com</li>
                <li><a href="http://www.hellyhansen.com">Public website</a> for leisure &amp; sportswear ranges.</li>
                <li><a href="http://www.hhworkwear.com">Public website</a> for industrial workwear range.</li>
                <li>Internal product management website.</li>
                <li>Internal document management website.</li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>

    <div class="sample">
        <div class="detail">
            <h4>Sense Internet <small>(Internal Tools)</small></h4>
            <ul class="compact">
                <li class="print">http://www.sense.co.uk</li>
                <li>SenseMax Intranet: Built UI for resource planner, calendar, address book, bug tracker, wiki.</li>
                <li>Hit Tracker: Collecting analytics data from ~75% of Sense's websites.</li>
                <li>Significant input into Sense's PHP MVC framework.</li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>

</div>

app/views/blog/date.html.erb
<h2><%= @title %></h2>

<%= render :partial=>'partials/entries', :object=>@entries %>

<% if @next or @prev -%>
    <% content_for :sidebar do -%>

        <h2>Other dates</h2>

        <ul id="metadata">
            <% if @prev -%>
                <% d_m_y = @prev.created_at.strftime(@format1) -%>
                <% y,m,d = @prev.created_at.strftime(@format2).split -%>
                <li class="prev"><%= link_to "Older entries from #{d_m_y}", date_url(:y=>y,:m=>m,:d=>d) -%></li>
            <% end -%>
            <% if @next -%>
                <% d_m_y = @next.created_at.strftime(@format1) -%>
                <% y,m,d = @next.created_at.strftime(@format2).split -%>
                <li class="next"><%= link_to "Newer entries from #{d_m_y}", date_url(:y=>y,:m=>m,:d=>d) -%></li>
            <% end -%>
        </ul>

        <p>Visit the <%= link_to 'archive', archive_url %> if you wish to skip merrily through time in a devil may care fashion.</p>

    <% end -%>
<% end -%>

app/views/blog/index.html.erb
<h2>Latest entries</h2>
<%= render(:partial=>'partials/entries', :object=>@entries) %>

<div class="hr"><hr /></div>

<p>
    <%= link_to(date_url(:y=>@first_date.year, :m=>@first_date.month)) do %>
        &larr; Archived entries by month
    <% end %>
</p>


<% content_for :sidebar do -%>
    <h2>Where am I?</h2>

    <p>
    The personal site of <%= link_to 'Matthew Tarbit', about_url %>, a seasoned
    web developer holed-up in a hideaway somewhere in the depths of Leeds, England.
    </p>

    <div class="hr"><hr /></div>

    <%= render(:partial=>'partials/reading', :object=>@books) %>
<% end -%>

app/views/blog/notfound.html.erb
<h2>404 not found</h2>

<div class="section">
    <h3>You look lost</h3>
    <p>I'm not sure what you're searching for, but whatever it is, you've come to the wrong place.</p>
    <p>Maybe you'll have better luck over there. In the sidebar. To your right.</p>
</div>
<div class="section">
    <style type="text/css">
        #goog-wm h3.closest-match { }
        #goog-wm h3.closest-match a { }
        #goog-wm h3.other-things b { font-weight:normal; }
        #goog-wm ul { padding:0; margin:0; }
        #goog-wm ul li { padding:0; margin:0; }
        #goog-wm li.search-goog { display: block; border:1px solid #ddd; background:url(/images/fades/pale.gif) repeat-x top #f2f2f2; margin:1em 0; padding:1em; padding-top:0.5em; }
        #goog-wm-qt { width:270px; margin-right:10px; margin-top:5px; }
        #goog-wm-sb { border:1px solid #333; background:url(/images/fades/dark.gif) repeat-x top #333; color:#fff; }
    </style>
    <script type="text/javascript">
        var GOOG_FIXURL_LANG = 'en';
        var GOOG_FIXURL_SITE = 'http://matt.tarbit.org/';
    </script>
    <script type="text/javascript" src="http://linkhelp.clients.google.com/tbproxy/lh/wm/fixurl.js"></script>
</div>

app/views/blog/search.html.erb
<h2><%= @title %></h2>

<%= form_tag do %>

    <fieldset>
        <legend>Search Details</legend>

        <div class="form-row">
            <div class="label"><label for="words">Words:</label></div>
            <div class="input">
                <%= text_field_tag :words, params[:words], :style=>'width:200px', :size=>75 %>
                &nbsp;
                <%= submit_tag 'Submit', {:class=>'button'} %>
            </div>
        </div>

    </fieldset>

<% end %>

<%= render :partial => 'partials/entries', :locals => { :entries => @entries, :words => @words } %>